FROM node:22.8.0 as builder
ADD pkg/ui/package*.json /opt/ui/
WORKDIR /opt/ui
# RUN npm install
RUN npm install
COPY pkg/ui /opt/ui
RUN npm run build
#RUN npx parcel build src/index.js

FROM nginx:alpine
COPY --from=builder /opt/ui/dist /var/www
COPY pkg/ui/default.nginx.conf /etc/nginx/conf.d/
COPY pkg/ui/nginx.conf /etc/nginx/
RUN rm -rf /etc/nginx/conf.d/default.conf

RUN adduser 1001 -g 1000 -D
RUN chown 1001:1000 -R /var/www
RUN chown 1001:1000 -R /etc/nginx
RUN mkdir -p /tmp/config && chown 1001:1000 -R /tmp/config
RUN mkdir -p /tmp/devices && chown 1001:1000 -R /tmp/devices

USER 1001

COPY pkg/ui/docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
