usecases:
  - ID: 1
    Description: "FlashStack use case1"
    Server_Type: "Fabric Interconnect"
    Server_Count: 40
    Switch_Type: "MDS"
    Switch_Count: 2
    Storage_Type: "Flash Array"
    Storage_Count: 1


  - ID: 2
    Description: "FlashStack use case2"
    Server_Type: "Fabric Interconnect"
    Server_Count: 2
    Switch_Type: "MDS"
    Switch_Count: 2
    Storage_Type: "Flash Array"
    Storage_Count: 100
  
  - ID: 3
    Description: "FlashStack use case3"
    Server_Type: "Fabric Interconnect"
    Server_Count: 2
    Switch_Type: "Nexus 9K"
    Switch_Count: 2
    Storage_Type: "Flash Array"
    Storage_Count: 2

  - ID: 4
    Server_Type: "Fabric Interconnect"
    Server_Count: 2
    Description: "FlashStack use case4"
    Switch_Type: "MDS"
    Switch_Count: 100
    Storage_Type: "Flash Array"
    Storage_Count: 2

  - ID: 5
    Server_Type: "Fabric Interconnect"
    Server_Count: 2
    Description: "FlashStack use case5"
    Switch_Type: "MDS"
    Switch_Count: 5
    Storage_Type: "Flash Array"
    Storage_Count: 2
